### ISSUE TITLE
onos

### ISSUE THREAD

**Issue by 1760947562** [onosproject/onos-control#13]
I installed onos2.2.0 and soft P4 switches respectively. Soft P4 switches include BMV2, P4c, protobuf, etc. How can I use onos to control BMV2? What command should I use to complete the connection between onos and BMV2? Do I need to start BMV2 before connecting?

**Comment by adibrastegarnia** [comment]
@1760947562 
This repo is for next generation of onos and it is in early stages of development. You question is related to the current version of onos. I would suggest to ask your questions related to current version of onos in onos mailing lists:
https://onosproject.org/contribute/mailing-lists/
